name: cmh-deploy-gh-pages
# reference
#   https://github.com/PreTeXtBook/pretext-cli/blob/main/.github/workflows/codespace-template.yml
#   https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/utils.py
on:
  push:

jobs:
  cmh-preTeXt-build:
    runs-on: ubuntu-latest
    steps:
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install pretext
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install --upgrade pretext
      - name: load the "base actions/checkout" so as to access cmh-preTeXt-explore
        uses: actions/checkout@v4
      - name: cmh-build-html
        run: pretext build web
      - name: cmh-deploy-html
        run: pretext deploy
  # Deploy job
  cmh-preTeXt-deploy-gh-pages:
    # Add a dependency to the build job
    needs: cmh-preTeXt-build

    artifact_name: output/web
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action